from __future__ import annotations

from typing import Any

from app.calculators.extended_validation import (
    EXTENDED_PARAMETER_OVERRIDES,
    EXTENDED_VALIDATION_OVERRIDES,
)


def _doc(name: str, example_input: dict[str, Any]) -> dict[str, Any]:
    return {
        "parameter_notes": f"{name} 支持输入总分，部分量表也支持按条目分值求和。",
        "usage_examples": [{"input": example_input, "description": f"{name} 示例"}],
        "reference_literature": [f"{name} 常用公开评分分层标准"],
        "update_record": ["2026-04-28：接入第一批扩展计算器运行时实现。"],
    }


def build_extended_manifests() -> list[dict[str, Any]]:
    priority_high = {
        "home_suitability": 0.9,
        "clinical_importance": 0.9,
        "implementation_simplicity": 0.85,
        "chinese_support": 1.0,
    }

    manifests = [
        {
            "name": "phq9",
            "display_name": "PHQ-9 抑郁筛查",
            "description": "根据 PHQ-9 总分或各条目分值评估抑郁症状负担。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_phq9",
            "intent_keywords": ["phq9", "phq-9", "抑郁", "情绪量表"],
            "required_params": ["total_score"],
            "optional_params": [f"phq9_q{i}" for i in range(1, 10)],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 27, "description": "PHQ-9 总分"}],
            "reference": "PHQ-9 常用分层标准。",
            "applicable_scenario": "居家情绪筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("PHQ-9 抑郁筛查", {"total_score": 12}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "gad7",
            "display_name": "GAD-7 焦虑筛查",
            "description": "根据 GAD-7 总分或各条目分值评估焦虑症状负担。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_gad7",
            "intent_keywords": ["gad7", "gad-7", "焦虑", "情绪量表"],
            "required_params": ["total_score"],
            "optional_params": [f"gad7_q{i}" for i in range(1, 8)],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 21, "description": "GAD-7 总分"}],
            "reference": "GAD-7 常用分层标准。",
            "applicable_scenario": "居家焦虑筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("GAD-7 焦虑筛查", {"total_score": 10}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "qsofa",
            "display_name": "qSOFA 评分",
            "description": "根据呼吸频率、收缩压和意识状态快速评估感染相关高风险。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_qsofa",
            "intent_keywords": ["qsofa", "感染", "脓毒症", "qsofa评分"],
            "required_params": ["respiratory_rate_bpm", "systolic_bp", "altered_mental_status"],
            "optional_params": ["gcs_score"],
            "parameters": [
                {"name": "respiratory_rate_bpm", "label": "呼吸频率", "type": "float", "required": True, "min": 5, "max": 80, "unit": "次/分", "description": "呼吸频率"},
                {"name": "systolic_bp", "label": "收缩压", "type": "float", "required": True, "min": 50, "max": 300, "unit": "mmHg", "description": "收缩压"},
                {"name": "altered_mental_status", "label": "意识改变", "type": "str", "required": True, "description": "是否存在意识状态改变"},
            ],
            "reference": "qSOFA 常用分层标准。",
            "applicable_scenario": "感染高风险快速筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.98,
            "priority": priority_high,
            "documentation": _doc("qSOFA 评分", {"respiratory_rate_bpm": 24, "systolic_bp": 95, "altered_mental_status": "是"}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "news2",
            "display_name": "NEWS2 早期预警评分",
            "description": "依据生命体征综合计算 NEWS2 评分。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_news2",
            "intent_keywords": ["news2", "news", "预警评分", "生命体征"],
            "required_params": ["respiratory_rate_bpm", "oxygen_saturation", "temperature_c", "systolic_bp", "heart_rate_bpm", "consciousness"],
            "optional_params": ["supplemental_oxygen"],
            "parameters": [
                {"name": "respiratory_rate_bpm", "label": "呼吸频率", "type": "float", "required": True, "min": 5, "max": 80, "unit": "次/分", "description": "呼吸频率"},
                {"name": "oxygen_saturation", "label": "血氧饱和度", "type": "float", "required": True, "min": 50, "max": 100, "unit": "%", "description": "脉搏血氧饱和度"},
                {"name": "temperature_c", "label": "体温", "type": "float", "required": True, "min": 30, "max": 45, "unit": "℃", "description": "体温"},
                {"name": "systolic_bp", "label": "收缩压", "type": "float", "required": True, "min": 50, "max": 300, "unit": "mmHg", "description": "收缩压"},
                {"name": "heart_rate_bpm", "label": "心率", "type": "float", "required": True, "min": 20, "max": 220, "unit": "次/分", "description": "心率"},
                {"name": "consciousness", "label": "意识状态", "type": "str", "required": True, "description": "A/V/P/U 或文字描述"},
            ],
            "reference": "NEWS2 常用评分分层标准。",
            "applicable_scenario": "居家病情恶化风险预警",
            "supports_chinese": True,
            "clinical_specificity": 0.99,
            "priority": priority_high,
            "documentation": _doc("NEWS2 早期预警评分", {"respiratory_rate_bpm": 24, "oxygen_saturation": 92, "temperature_c": 38.2, "systolic_bp": 96, "heart_rate_bpm": 118, "consciousness": "A"}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "barthel_index",
            "display_name": "Barthel 指数",
            "description": "根据 Barthel 总分评估日常生活活动能力。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_barthel_index",
            "intent_keywords": ["barthel", "barthel指数", "日常生活能力", "adl"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 100, "description": "Barthel 总分"}],
            "reference": "Barthel 指数常用分层标准。",
            "applicable_scenario": "居家功能状态评估",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Barthel 指数", {"total_score": 65}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "pain_nrs",
            "display_name": "疼痛 NRS 评分",
            "description": "根据 0-10 分数字评分法评估疼痛程度。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_pain_nrs",
            "intent_keywords": ["疼痛", "nrs", "疼痛评分", "痛感"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 10, "description": "疼痛 NRS 分数"}],
            "reference": "疼痛 NRS 常用分层标准。",
            "applicable_scenario": "居家疼痛监测",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("疼痛 NRS 评分", {"total_score": 7}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "mmrc",
            "display_name": "mMRC 呼吸困难分级",
            "description": "根据 mMRC 分级评估呼吸困难程度。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_mmrc",
            "intent_keywords": ["mmrc", "呼吸困难", "气短", "慢阻肺"],
            "required_params": ["grade"],
            "optional_params": [],
            "parameters": [{"name": "grade", "label": "分级", "type": "float", "required": True, "min": 0, "max": 4, "description": "mMRC 分级"}],
            "reference": "mMRC 分级标准。",
            "applicable_scenario": "呼吸困难症状评估",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("mMRC 呼吸困难分级", {"grade": 2}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "cat",
            "display_name": "CAT 慢阻肺评估测试",
            "description": "根据 CAT 总分或各条目分值评估呼吸症状负担。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_cat",
            "intent_keywords": ["cat", "慢阻肺", "呼吸症状", "cat评分"],
            "required_params": ["total_score"],
            "optional_params": [f"cat_q{i}" for i in range(1, 9)],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 40, "description": "CAT 总分"}],
            "reference": "CAT 常用分层标准。",
            "applicable_scenario": "慢阻肺症状负担评估",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("CAT 慢阻肺评估测试", {"total_score": 18}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "cha2ds2_vasc",
            "display_name": "CHA2DS2-VASc 卒中风险评分",
            "description": "用于房颤相关卒中风险评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_cha2ds2_vasc",
            "intent_keywords": ["cha2ds2-vasc", "cha2ds2_vasc", "房颤卒中", "卒中风险评分"],
            "required_params": ["age", "gender", "congestive_heart_failure", "hypertension", "diabetes", "prior_stroke_tia_thromboembolism", "vascular_disease"],
            "optional_params": [],
            "parameters": [
                {"name": "age", "label": "年龄", "type": "float", "required": True, "min": 0, "max": 120, "description": "年龄"},
                {"name": "gender", "label": "性别", "type": "str", "required": True, "description": "男或女"},
            ],
            "reference": "CHA2DS2-VASc 常用评分标准。",
            "applicable_scenario": "房颤卒中风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.98,
            "priority": priority_high,
            "documentation": _doc("CHA2DS2-VASc 卒中风险评分", {"age": 76, "gender": "女", "hypertension": True, "diabetes": True, "prior_stroke_tia_thromboembolism": False, "vascular_disease": False, "congestive_heart_failure": False}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "has_bled",
            "display_name": "HAS-BLED 出血风险评分",
            "description": "用于抗凝相关出血风险评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_has_bled",
            "intent_keywords": ["has-bled", "has_bled", "出血风险", "抗凝"],
            "required_params": ["age", "uncontrolled_hypertension", "abnormal_renal_function", "abnormal_liver_function", "prior_stroke", "bleeding_history", "labile_inr", "drugs_predisposing_bleeding", "alcohol_excess"],
            "optional_params": ["systolic_bp"],
            "parameters": [{"name": "age", "label": "年龄", "type": "float", "required": True, "min": 0, "max": 120, "description": "年龄"}],
            "reference": "HAS-BLED 常用评分标准。",
            "applicable_scenario": "抗凝出血风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.98,
            "priority": priority_high,
            "documentation": _doc("HAS-BLED 出血风险评分", {"age": 70, "uncontrolled_hypertension": True, "abnormal_renal_function": False, "abnormal_liver_function": False, "prior_stroke": True, "bleeding_history": False, "labile_inr": False, "drugs_predisposing_bleeding": True, "alcohol_excess": False}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "chads2",
            "display_name": "CHADS2 卒中风险评分",
            "description": "用于房颤相关卒中风险评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_chads2",
            "intent_keywords": ["chads2", "房颤卒中", "卒中评分"],
            "required_params": ["age", "congestive_heart_failure", "hypertension", "diabetes", "prior_stroke_tia"],
            "optional_params": [],
            "parameters": [{"name": "age", "label": "年龄", "type": "float", "required": True, "min": 0, "max": 120, "description": "年龄"}],
            "reference": "CHADS2 常用评分标准。",
            "applicable_scenario": "房颤卒中风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.97,
            "priority": priority_high,
            "documentation": _doc("CHADS2 卒中风险评分", {"age": 78, "congestive_heart_failure": False, "hypertension": True, "diabetes": True, "prior_stroke_tia": False}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "wells_dvt",
            "display_name": "Wells DVT 评分",
            "description": "用于深静脉血栓临床可能性评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_wells_dvt",
            "intent_keywords": ["wells dvt", "wells_dvt", "深静脉血栓", "dvt"],
            "required_params": ["active_cancer", "paralysis_or_recent_cast", "bedridden_or_recent_surgery", "localized_tenderness", "entire_leg_swollen", "calf_swelling_gt_3cm", "pitting_edema", "collateral_superficial_veins", "previous_dvt", "alternative_diagnosis_more_likely"],
            "optional_params": [],
            "parameters": [],
            "reference": "Wells DVT 常用评分标准。",
            "applicable_scenario": "静脉血栓风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("Wells DVT 评分", {"active_cancer": False, "paralysis_or_recent_cast": False, "bedridden_or_recent_surgery": True, "localized_tenderness": True, "entire_leg_swollen": True, "calf_swelling_gt_3cm": False, "pitting_edema": True, "collateral_superficial_veins": False, "previous_dvt": False, "alternative_diagnosis_more_likely": False}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "wells_pe",
            "display_name": "Wells PE 评分",
            "description": "用于肺栓塞临床可能性评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_wells_pe",
            "intent_keywords": ["wells pe", "wells_pe", "肺栓塞", "pe评分"],
            "required_params": ["clinical_signs_dvt", "pe_more_likely_than_alternative", "heart_rate_bpm", "immobilization_or_recent_surgery", "previous_dvt_pe", "hemoptysis", "malignancy"],
            "optional_params": [],
            "parameters": [{"name": "heart_rate_bpm", "label": "心率", "type": "float", "required": True, "min": 20, "max": 220, "description": "心率"}],
            "reference": "Wells PE 常用评分标准。",
            "applicable_scenario": "肺栓塞风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("Wells PE 评分", {"clinical_signs_dvt": True, "pe_more_likely_than_alternative": True, "heart_rate_bpm": 112, "immobilization_or_recent_surgery": False, "previous_dvt_pe": False, "hemoptysis": False, "malignancy": False}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "heart_score",
            "display_name": "HEART 胸痛风险评分",
            "description": "用于胸痛短期主要心血管不良事件风险分层。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_heart_score",
            "intent_keywords": ["heart score", "heart_score", "胸痛评分", "heart评分"],
            "required_params": ["history_score", "ecg_score", "troponin_score", "age", "risk_factor_count"],
            "optional_params": ["known_atherosclerotic_disease", "total_score"],
            "parameters": [
                {"name": "history_score", "label": "病史评分", "type": "float", "required": True, "min": 0, "max": 2, "description": "病史项评分"},
                {"name": "ecg_score", "label": "心电图评分", "type": "float", "required": True, "min": 0, "max": 2, "description": "心电图项评分"},
                {"name": "troponin_score", "label": "肌钙蛋白评分", "type": "float", "required": True, "min": 0, "max": 2, "description": "肌钙蛋白项评分"},
                {"name": "age", "label": "年龄", "type": "float", "required": True, "min": 0, "max": 120, "description": "年龄"},
                {"name": "risk_factor_count", "label": "危险因素数量", "type": "float", "required": True, "min": 0, "max": 10, "description": "危险因素数量"},
            ],
            "reference": "HEART 常用评分标准。",
            "applicable_scenario": "胸痛风险分层",
            "supports_chinese": True,
            "clinical_specificity": 0.97,
            "priority": priority_high,
            "documentation": _doc("HEART 胸痛风险评分", {"history_score": 2, "ecg_score": 1, "troponin_score": 1, "age": 66, "risk_factor_count": 3}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "findrisc",
            "display_name": "FINDRISC 糖尿病风险评分",
            "description": "用于未来糖尿病风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_findrisc",
            "intent_keywords": ["findrisc", "糖尿病风险", "findrisc评分"],
            "required_params": ["age", "bmi", "waist_cm", "gender", "physically_active_daily", "daily_fruits_vegetables", "antihypertensive_medication", "history_high_blood_glucose", "family_history_diabetes"],
            "optional_params": [],
            "parameters": [
                {"name": "age", "label": "年龄", "type": "float", "required": True, "min": 0, "max": 120, "description": "年龄"},
                {"name": "bmi", "label": "BMI", "type": "float", "required": True, "min": 10, "max": 80, "description": "BMI"},
                {"name": "waist_cm", "label": "腰围", "type": "float", "required": True, "min": 30, "max": 200, "description": "腰围"},
                {"name": "gender", "label": "性别", "type": "str", "required": True, "description": "男或女"},
            ],
            "reference": "FINDRISC 常用评分标准。",
            "applicable_scenario": "糖尿病风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("FINDRISC 糖尿病风险评分", {"age": 58, "bmi": 29, "waist_cm": 96, "gender": "男", "physically_active_daily": False, "daily_fruits_vegetables": False, "antihypertensive_medication": True, "history_high_blood_glucose": False, "family_history_diabetes": "first_degree"}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "metabolic_syndrome",
            "display_name": "代谢综合征评分",
            "description": "依据中心性肥胖、血压、血糖和血脂异常进行综合评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_metabolic_syndrome",
            "intent_keywords": ["代谢综合征", "metabolic syndrome", "血脂血糖血压"],
            "required_params": ["waist_cm", "gender", "systolic_bp", "diastolic_bp", "fasting_glucose", "triglycerides_mmol_l", "hdl_mmol_l"],
            "optional_params": [],
            "parameters": [
                {"name": "waist_cm", "label": "腰围", "type": "float", "required": True, "min": 30, "max": 200, "description": "腰围"},
                {"name": "gender", "label": "性别", "type": "str", "required": True, "description": "男或女"},
                {"name": "systolic_bp", "label": "收缩压", "type": "float", "required": True, "min": 50, "max": 300, "description": "收缩压"},
                {"name": "diastolic_bp", "label": "舒张压", "type": "float", "required": True, "min": 30, "max": 200, "description": "舒张压"},
                {"name": "fasting_glucose", "label": "空腹血糖", "type": "float", "required": True, "min": 1, "max": 50, "description": "空腹血糖"},
                {"name": "triglycerides_mmol_l", "label": "甘油三酯", "type": "float", "required": True, "min": 0.1, "max": 50, "description": "甘油三酯"},
                {"name": "hdl_mmol_l", "label": "HDL", "type": "float", "required": True, "min": 0.1, "max": 10, "description": "高密度脂蛋白胆固醇"},
            ],
            "reference": "代谢综合征常用筛查标准。",
            "applicable_scenario": "代谢风险综合筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("代谢综合征评分", {"waist_cm": 96, "gender": "男", "systolic_bp": 138, "diastolic_bp": 88, "fasting_glucose": 6.0, "triglycerides_mmol_l": 2.1, "hdl_mmol_l": 0.9}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "nafld_fibrosis",
            "display_name": "NAFLD 纤维化评分",
            "description": "依据年龄、BMI 和实验室指标评估 NAFLD 进展性纤维化风险。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_nafld_fibrosis",
            "intent_keywords": ["nafld fibrosis", "nafld_fibrosis", "脂肪肝纤维化", "nfs"],
            "required_params": ["age", "bmi", "ast_u_l", "alt_u_l", "platelet_10e9_l", "albumin_g_dl", "impaired_fasting_glucose_or_diabetes"],
            "optional_params": [],
            "parameters": [
                {"name": "age", "label": "年龄", "type": "float", "required": True, "min": 0, "max": 120, "description": "年龄"},
                {"name": "bmi", "label": "BMI", "type": "float", "required": True, "min": 10, "max": 80, "description": "BMI"},
                {"name": "ast_u_l", "label": "AST", "type": "float", "required": True, "min": 1, "max": 5000, "description": "AST"},
                {"name": "alt_u_l", "label": "ALT", "type": "float", "required": True, "min": 1, "max": 5000, "description": "ALT"},
                {"name": "platelet_10e9_l", "label": "血小板", "type": "float", "required": True, "min": 1, "max": 2000, "description": "血小板计数"},
                {"name": "albumin_g_dl", "label": "白蛋白", "type": "float", "required": True, "min": 0.5, "max": 10, "description": "白蛋白"},
            ],
            "reference": "NAFLD fibrosis score 原始公式阈值。",
            "applicable_scenario": "脂肪肝纤维化风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("NAFLD 纤维化评分", {"age": 58, "bmi": 31.2, "ast_u_l": 42, "alt_u_l": 35, "platelet_10e9_l": 180, "albumin_g_dl": 4.0, "impaired_fasting_glucose_or_diabetes": True}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "morse_fall_scale",
            "display_name": "Morse 跌倒量表",
            "description": "用于老年与住院照护场景下的跌倒风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_morse_fall_scale",
            "intent_keywords": ["morse", "跌倒量表", "跌倒风险"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 125, "description": "Morse 总分"}],
            "reference": "Morse Fall Scale 常用评分标准。",
            "applicable_scenario": "跌倒风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Morse 跌倒量表", {"total_score": 55}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "braden_scale",
            "display_name": "Braden 压疮风险评分",
            "description": "用于压疮风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_braden_scale",
            "intent_keywords": ["braden", "压疮", "压疮风险"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 6, "max": 23, "description": "Braden 总分"}],
            "reference": "Braden Scale 常用评分标准。",
            "applicable_scenario": "压疮风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Braden 压疮风险评分", {"total_score": 12}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "mna_sf",
            "display_name": "MNA-SF 营养评估",
            "description": "用于老年营养不良风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_mna_sf",
            "intent_keywords": ["mna-sf", "mna_sf", "营养评估", "营养不良"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 14, "description": "MNA-SF 总分"}],
            "reference": "MNA-SF 常用评分标准。",
            "applicable_scenario": "老年营养筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("MNA-SF 营养评估", {"total_score": 9}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "gds15",
            "display_name": "GDS-15 老年抑郁量表",
            "description": "用于老年抑郁症状筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_gds15",
            "intent_keywords": ["gds15", "gds-15", "老年抑郁", "情绪筛查"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 15, "description": "GDS-15 总分"}],
            "reference": "GDS-15 常用评分标准。",
            "applicable_scenario": "老年情绪筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("GDS-15 老年抑郁量表", {"total_score": 10}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "tug_test",
            "display_name": "TUG 起立行走测试",
            "description": "用于功能移动性与跌倒风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_tug_test",
            "intent_keywords": ["tug", "起立行走", "timed up and go", "跌倒测试"],
            "required_params": ["time_seconds"],
            "optional_params": [],
            "parameters": [{"name": "time_seconds", "label": "用时", "type": "float", "required": True, "min": 1, "max": 300, "description": "完成 TUG 的秒数"}],
            "reference": "TUG 常用参考阈值。",
            "applicable_scenario": "跌倒风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("TUG 起立行走测试", {"time_seconds": 14.2}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "ad8",
            "display_name": "AD8 认知筛查",
            "description": "用于认知异常风险快速筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_ad8",
            "intent_keywords": ["ad8", "认知筛查", "记忆下降"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 8, "description": "AD8 总分"}],
            "reference": "AD8 常用评分标准。",
            "applicable_scenario": "认知异常筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("AD8 认知筛查", {"total_score": 3}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "mini_cog",
            "display_name": "Mini-Cog 认知筛查",
            "description": "基于三词回忆和画钟试验进行认知风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_mini_cog",
            "intent_keywords": ["mini-cog", "mini_cog", "画钟", "认知筛查"],
            "required_params": ["recall_score", "clock_normal"],
            "optional_params": [],
            "parameters": [
                {"name": "recall_score", "label": "回忆得分", "type": "float", "required": True, "min": 0, "max": 3, "description": "三词回忆得分"},
                {"name": "clock_normal", "label": "画钟是否正常", "type": "str", "required": True, "description": "是或否"},
            ],
            "reference": "Mini-Cog 官方评分规则。",
            "applicable_scenario": "认知异常筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Mini-Cog 认知筛查", {"recall_score": 1, "clock_normal": False}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "fried_frailty",
            "display_name": "Fried 衰弱表型评分",
            "description": "用于身体衰弱状态分层。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_fried_frailty",
            "intent_keywords": ["fried frailty", "fried_frailty", "衰弱", "frailty"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 5, "description": "Fried 衰弱表型得分"}],
            "reference": "Fried frailty phenotype 常用分层标准。",
            "applicable_scenario": "衰弱筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Fried 衰弱表型评分", {"total_score": 3}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "lawton_iadl",
            "display_name": "Lawton IADL 量表",
            "description": "用于工具性日常生活能力评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_lawton_iadl",
            "intent_keywords": ["lawton iadl", "lawton_iadl", "iadl", "工具性日常生活能力"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 8, "description": "Lawton IADL 总分"}],
            "reference": "Lawton IADL 常用评分标准。",
            "applicable_scenario": "功能状态评估",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("Lawton IADL 量表", {"total_score": 4}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "sarc_f",
            "display_name": "SARC-F 肌少症筛查",
            "description": "用于肌少症风险快速筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_sarc_f",
            "intent_keywords": ["sarc-f", "sarc_f", "肌少症", "肌力下降"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 10, "description": "SARC-F 总分"}],
            "reference": "SARC-F 常用评分标准。",
            "applicable_scenario": "肌少症风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("SARC-F 肌少症筛查", {"total_score": 5}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "rockwood_cfs",
            "display_name": "Rockwood 临床衰弱量表",
            "description": "用于老年综合衰弱程度分层。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_rockwood_cfs",
            "intent_keywords": ["rockwood", "cfs", "临床衰弱量表", "frailty scale"],
            "required_params": ["grade"],
            "optional_params": [],
            "parameters": [{"name": "grade", "label": "分级", "type": "float", "required": True, "min": 1, "max": 9, "description": "Clinical Frailty Scale 分级"}],
            "reference": "Clinical Frailty Scale 常用分层标准。",
            "applicable_scenario": "综合衰弱评估",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Rockwood 临床衰弱量表", {"grade": 6}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "karnofsky_ps",
            "display_name": "Karnofsky 体能状态评分",
            "description": "用于功能状态和照护依赖程度评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_karnofsky_ps",
            "intent_keywords": ["karnofsky", "kps", "体能状态", "功能状态"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 100, "description": "Karnofsky 总分"}],
            "reference": "Karnofsky Performance Status 常用评分标准。",
            "applicable_scenario": "功能状态评估",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("Karnofsky 体能状态评分", {"total_score": 60}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "cdrs",
            "display_name": "CDRS 糖尿病风险评分",
            "description": "用于中国成人糖尿病风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_cdrs",
            "intent_keywords": ["cdrs", "中国糖尿病风险评分", "糖尿病高危"],
            "required_params": ["age", "bmi", "waist_cm", "systolic_bp", "gender", "family_history_diabetes"],
            "optional_params": [],
            "parameters": [],
            "reference": "中国糖尿病风险评分表。",
            "applicable_scenario": "糖尿病风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("CDRS 糖尿病风险评分", {"age": 58, "bmi": 28, "waist_cm": 92, "systolic_bp": 142, "gender": "男", "family_history_diabetes": True}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "nihss",
            "display_name": "NIHSS 神经功能缺损评分",
            "description": "用于卒中相关神经功能缺损程度分层。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_nihss",
            "intent_keywords": ["nihss", "卒中评分", "神经功能缺损"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 42, "description": "NIHSS 总分"}],
            "reference": "NIHSS 常用分层标准。",
            "applicable_scenario": "神经功能评估",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("NIHSS 神经功能缺损评分", {"total_score": 18}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "glasgow_coma_scale",
            "display_name": "Glasgow 昏迷评分",
            "description": "用于意识状态评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_glasgow_coma_scale",
            "intent_keywords": ["gcs", "glasgow", "昏迷评分", "意识状态"],
            "required_params": ["gcs_score"],
            "optional_params": ["eye_score", "verbal_score", "motor_score"],
            "parameters": [{"name": "gcs_score", "label": "总分", "type": "float", "required": True, "min": 3, "max": 15, "description": "GCS 总分"}],
            "reference": "Glasgow Coma Scale 常用分层标准。",
            "applicable_scenario": "意识状态评估",
            "supports_chinese": True,
            "clinical_specificity": 0.96,
            "priority": priority_high,
            "documentation": _doc("Glasgow 昏迷评分", {"gcs_score": 7}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "must",
            "display_name": "MUST 营养不良筛查",
            "description": "用于营养不良风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_must",
            "intent_keywords": ["must", "营养不良", "营养筛查"],
            "required_params": ["total_score"],
            "optional_params": ["bmi", "weight_loss_percent", "acute_disease_effect"],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 10, "description": "MUST 总分"}],
            "reference": "MUST 常用评分标准。",
            "applicable_scenario": "营养风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("MUST 营养不良筛查", {"total_score": 2}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "caprini_vte",
            "display_name": "Caprini 血栓风险评分",
            "description": "用于静脉血栓栓塞风险评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_caprini_vte",
            "intent_keywords": ["caprini", "血栓风险", "vte评分"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 40, "description": "Caprini 总分"}],
            "reference": "Caprini 常用评分标准。",
            "applicable_scenario": "血栓风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("Caprini 血栓风险评分", {"total_score": 6}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "mews",
            "display_name": "MEWS 早期预警评分",
            "description": "用于病情恶化风险早期预警。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_mews",
            "intent_keywords": ["mews", "预警评分", "生命体征"],
            "required_params": ["total_score"],
            "optional_params": ["respiratory_rate_bpm", "temperature_c", "systolic_bp", "heart_rate_bpm", "consciousness"],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 20, "description": "MEWS 总分"}],
            "reference": "MEWS 常用评分标准。",
            "applicable_scenario": "病情恶化风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.95,
            "priority": priority_high,
            "documentation": _doc("MEWS 早期预警评分", {"total_score": 6}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "charlson_cci",
            "display_name": "Charlson 合并症指数",
            "description": "用于基础病负担评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_charlson_cci",
            "intent_keywords": ["charlson", "cci", "合并症指数", "基础病负担"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 50, "description": "Charlson 总分"}],
            "reference": "Charlson Comorbidity Index 常用分层。",
            "applicable_scenario": "基础病负担评估",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("Charlson 合并症指数", {"total_score": 5}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "norton_scale",
            "display_name": "Norton 压疮风险评分",
            "description": "用于压疮风险筛查。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_norton_scale",
            "intent_keywords": ["norton", "压疮风险", "压疮评分"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 5, "max": 20, "description": "Norton 总分"}],
            "reference": "Norton Scale 常用评分标准。",
            "applicable_scenario": "压疮风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("Norton 压疮风险评分", {"total_score": 12}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "waterlow_score",
            "display_name": "Waterlow 压疮风险评分",
            "description": "用于压疮风险分层。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_waterlow_score",
            "intent_keywords": ["waterlow", "压疮风险", "waterlow评分"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 100, "description": "Waterlow 总分"}],
            "reference": "Waterlow 常用评分标准。",
            "applicable_scenario": "压疮风险筛查",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("Waterlow 压疮风险评分", {"total_score": 22}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "ascvd_10y",
            "display_name": "ASCVD 十年心血管风险",
            "description": "用于解释已获得的 ASCVD 十年风险百分比。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_ascvd_10y",
            "intent_keywords": ["ascvd", "十年风险", "心血管风险"],
            "required_params": ["risk_percent"],
            "optional_params": [],
            "parameters": [{"name": "risk_percent", "label": "风险百分比", "type": "float", "required": True, "min": 0, "max": 100, "description": "ASCVD 风险百分比"}],
            "reference": "ASCVD 常用风险分层阈值。",
            "applicable_scenario": "心血管风险分层",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("ASCVD 十年心血管风险", {"risk_percent": 12.4}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "timi",
            "display_name": "TIMI 风险评分",
            "description": "用于急性冠脉综合征风险分层。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_timi",
            "intent_keywords": ["timi", "冠脉风险", "timi评分"],
            "required_params": ["total_score"],
            "optional_params": [],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 14, "description": "TIMI 总分"}],
            "reference": "TIMI 常用风险分层。",
            "applicable_scenario": "急性冠脉综合征风险评估",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("TIMI 风险评分", {"total_score": 5}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "grace",
            "display_name": "GRACE 风险评分",
            "description": "用于解释 GRACE 总分或风险百分比。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_grace",
            "intent_keywords": ["grace", "冠脉预后", "grace评分"],
            "required_params": ["total_score"],
            "optional_params": ["risk_percent"],
            "parameters": [{"name": "total_score", "label": "总分", "type": "float", "required": True, "min": 0, "max": 400, "description": "GRACE 总分"}],
            "reference": "GRACE 常用风险分层阈值。",
            "applicable_scenario": "急性冠脉综合征预后评估",
            "supports_chinese": True,
            "clinical_specificity": 0.93,
            "priority": priority_high,
            "documentation": _doc("GRACE 风险评分", {"total_score": 150}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "qrisk3",
            "display_name": "QRISK3 心血管风险评分",
            "description": "用于解释已获得的 QRISK3 风险百分比。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_qrisk3",
            "intent_keywords": ["qrisk3", "qrisk", "心血管风险百分比"],
            "required_params": ["risk_percent"],
            "optional_params": [],
            "parameters": [{"name": "risk_percent", "label": "风险百分比", "type": "float", "required": True, "min": 0, "max": 100, "description": "QRISK3 风险百分比"}],
            "reference": "QRISK3 常用风险阈值。",
            "applicable_scenario": "心血管风险分层",
            "supports_chinese": True,
            "clinical_specificity": 0.9,
            "priority": priority_high,
            "documentation": _doc("QRISK3 心血管风险评分", {"risk_percent": 11.2}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
        {
            "name": "h2fpef",
            "display_name": "H2FPEF 评分",
            "description": "用于 HFpEF 概率评估。",
            "source_module": "app.calculators.extended",
            "function_name": "calculate_h2fpef",
            "intent_keywords": ["h2fpef", "hfpEF", "心衰概率"],
            "required_params": ["bmi", "antihypertensive_count", "atrial_fibrillation", "pulmonary_artery_systolic_pressure", "age", "e_over_e_prime"],
            "optional_params": [],
            "parameters": [],
            "reference": "H2FPEF 原始评分标准。",
            "applicable_scenario": "HFpEF 概率评估",
            "supports_chinese": True,
            "clinical_specificity": 0.94,
            "priority": priority_high,
            "documentation": _doc("H2FPEF 评分", {"bmi": 32.1, "antihypertensive_count": 2, "atrial_fibrillation": True, "pulmonary_artery_systolic_pressure": 42, "age": 68, "e_over_e_prime": 12}),
            "validation": {"unit_cases": [], "boundary_checks": []},
        },
    ]

    for manifest in manifests:
        if manifest["name"] in EXTENDED_PARAMETER_OVERRIDES:
            manifest["parameters"] = EXTENDED_PARAMETER_OVERRIDES[manifest["name"]]
        manifest["validation"] = EXTENDED_VALIDATION_OVERRIDES.get(
            manifest["name"],
            manifest.get("validation", {}),
        )

    return manifests
